/**:
    ros__parameters:
      video_device: "/dev/v4l/by-path/pci-0000:00:14.0-usb-0:3.2:1.0-video-index0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera3"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 960
      image_height: 540
      camera_name: "test_camera3"
      # reusing same camera intrinsics only for demo, should really be unique for camera3"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
